### ISSUE TITLE
Reference: List of every feature and interaction

### ISSUE THREAD

**Issue by AesaraB** [mypaint/mypaint#1225]
### Documentation source

https://github.com/mypaint/mypaint/blob/main/spec/features.toml

### Documentation issue

There currently isn't a list of every feature in MyPaint and their various properties and interactions to my knowledge.

A reference like this could be indispensable for the following tasks:
- Creation and maintenance of unit tests
- Creating user documentation

### Documentation suggestions

Begin by reading the user manual to see what things in MyPaint actually do.

Spitballing some kind of structure here.
```toml
[widgets]
description = "Interactive element in display"
[widgets.colour]
description = "Sets the colour property"
modified = 2020-01-01
[[widgets.colour.files]]
file="/gui/colour.py"
[[widgets.colour.capabilities]]
capability = "setColour"
capability = "openPopup"
```

It would be even better if we could automate this.

### MyPaint version

v3.0.0

### Code of Conduct

- [X] I acknowledge that my conduct contributes to shaping the community.
